import json
# (word, definition, example) - definitions and examples are OURS, written for this app.
VA = [
("paraphrase","say the same thing in your own words","Paraphrase what she said back to her before you answer."),
("ostensible","the stated reason, probably not the real one","His ostensible reason was the invoice, the real one was the reorder."),
("digress","wander off the point","I digress every time I talk without a structure."),
("uncanny","strange in a way that is hard to explain","His timing on that call was uncanny."),
("candor","open honesty even when it costs you","I appreciated the candor more than the answer."),
("morose","gloomy and withdrawn","Tight money makes me morose and people feel it."),
("adept","skilled at something through practice","He is adept at freight, so I defer to him."),
("saturated","completely full, can absorb no more","That category is saturated, there is no room for another me."),
("pragmatic","chooses what works over what is ideal","The pragmatic move is to ship half and wait."),
("congenial","pleasant and easy to be around","He is congenial, which is why the supplier calls go well."),
("quote","repeat someone's exact words, or state a price","Quote me the DDP number, not the EXW number."),
("plausible","believable on its face","Plausible is not the same as true."),
("specious","looks right but is actually false","That margin math is specious, it ignores the ad spend."),
("ingress","the way in","The ingress to the warehouse is on the north side."),
("egress","the way out","Every deal needs a defined egress before you sign."),
("straightforward","simple and direct, no tricks","Give me a straightforward answer on the ship date."),
("outspoken","says what they think in public","She is outspoken, which is useful and occasionally expensive."),
("forthright","says it straight without hedging","Be forthright about the money instead of hinting at it."),
("ingenuous","innocently honest, no hidden angle","His ingenuous question exposed the whole problem."),
("dolorous","full of sorrow","Do not send a dolorous follow up email, send a clear one."),
("lugubrious","exaggeratedly gloomy, almost comic about it","His lugubrious update made a two day delay sound fatal."),
("saturnine","gloomy and slow to warm","He is saturnine on the phone and fine in person."),
("optimistic","expects things to go well","Optimistic forecasts are how inventory dies."),
("jovial","cheerful and friendly","The jovial version of me closes more than the careful one."),
("sanguine","calmly confident that it will work out","I am sanguine about the quarter, not about the week."),
("sullen","silently resentful","I went sullen instead of saying what I wanted."),
("misanthropy","a general dislike of people","Burnout looks a lot like misanthropy from the outside."),
("deft","quick and skillful with a light touch","That was a deft way to say no."),
("adroit","clever and skillful, especially socially","He is adroit at changing the subject."),
("dexterous","skillful with the hands, or with a tricky situation","A dexterous answer got him out of the corner."),
("proficient","good enough to do the job well","I am proficient at PPC, I am not expert."),
("drenched","completely soaked","I came back from the trail walk drenched."),
("steeped","soaked in something long enough to take on its character","He is steeped in this category, twenty years of it."),
("permeated","spread through every part of something","The doubt permeated the whole conversation."),
("impregnated","filled through and through with something","The cloth is impregnated with the coating, not sprayed."),
("imbue","fill something with a quality","Imbue the listing with the reason it exists, not just specs."),
("sodden","heavy and soaked with liquid","The carton was sodden when it landed."),
("alien","completely foreign to how you normally are","Saying no felt alien, which is exactly the problem."),
("dissident","someone who openly disagrees with the group","Every good board needs one dissident."),
("incongruous","does not fit with what is around it","A premium price on a cheap photo is incongruous."),
]
out={
 "deck_id":"verbal_advantage",
 "deck_name":"Verbal Advantage",
 "version":1,
 "headword_source_url":"https://www.learnthat.org/word_lists/view/3927",
 "headword_source_note":"HEADWORDS ONLY, taken from the public LearnThat.org word list titled 'Verbal Advantage Word List' (retrieved 2026-09-06). The list is a study list associated with Charles Harrington Elster's 'Verbal Advantage: Ten Easy Steps to a Powerful Vocabulary'. No text from the book is reproduced here.",
 "definitions_note":"Every definition and every example sentence in this file was written for this app by automation-builder on 2026-09-06. Nothing is copied from the book.",
 "coverage_gap":"The book teaches 500 keywords across 10 levels. Only 40 headwords were retrievable from a citable public list on 2026-09-06 (learnthat.org lists 3927 and 25322 are the same 40 words; essentialenglish.review renders its per-level word pages in JavaScript and returns no words to a plain fetch). The remaining 460 headwords are NOT in this file and are NOT guessed. See the re-import hook in README.md.",
 "reimport_hook":"Drop the book in File Dump and run scripts/import_verbal_advantage.py to extract headwords only; the script then prints the words that still need our own definition and example.",
 "cards":[{"word":w,"definition":d,"example":e,"tier":1,"tier_label":"verbal advantage level 1"} for w,d,e in VA]
}
json.dump(out,open("data/words_va.json","w"),indent=0,ensure_ascii=True)
print("va cards:",len(VA), "unique:", len(set(w for w,_,_ in VA)))
