# Tier 1: precision verbs that replace vague ones
T1 = [
("mitigate","make something less bad or less severe","We can mitigate the delay by air shipping half the order."),
("delegate","hand a task to someone else and let them own it","I need to delegate the supplier follow ups instead of doing all of them myself."),
("corroborate","back up a claim with a second piece of evidence","The Keepa chart corroborates what the seller told me about his price drop."),
("curtail","cut something back before it gets out of hand","I curtailed the ad spend on that campaign before it burned another week."),
("reconcile","make two sets of numbers agree","I still have to reconcile the supplier statement against what we actually wired."),
("escalate","move an issue up to someone with more authority","If they miss the ship date again I escalate it to the factory owner."),
("defer","put something off on purpose, not by accident","I am deferring the reorder until the sell through data comes in."),
("clarify","make something plainer so nobody guesses","Let me clarify what I am asking for so we do not waste a week."),
("consolidate","pull scattered things into one place","I consolidated four spreadsheets into one so the numbers stop disagreeing."),
("substantiate","prove a claim with real backing","He can say the margin is thirty percent, but he has to substantiate it."),
("expedite","make something happen faster than normal","I paid to expedite the sample so we could test it this week."),
("allocate","assign money or time to a specific job","I allocate two hundred a day to that portfolio and nothing more."),
("verify","check that something is actually true","Verify the tracking number before you tell me the pallet shipped."),
("prioritize","decide what goes first and mean it","I have to prioritize the cash problems before the fun projects."),
("streamline","strip the steps that do not earn their place","We streamlined the intake so it takes five minutes instead of thirty."),
("forecast","estimate what happens next from what already happened","My forecast says we run out of stock in six weeks at this velocity."),
("dispute","formally push back on a charge or claim","I am going to dispute the freight surcharge, it was never quoted."),
("waive","give up a right or a fee on purpose","He waived the tooling fee to win the second order."),
("retract","take back something you said","I retracted the offer once I saw the real landed cost."),
("concede","admit the other side has a point","I will concede the timeline was tight, but the spec never changed."),
("acknowledge","say out loud that you heard or saw something","Acknowledge what she said before you jump to your answer."),
("anticipate","see it coming and get ahead of it","I anticipated the port delay and moved the order up two weeks."),
("designate","name a specific person or thing for a job","Designate one person to own the reply or nobody replies."),
("authorize","give official permission","Only I authorize a wire over five thousand."),
("override","cancel a normal rule with a higher one","I overrode the bid cap for one week to hold rank."),
("postpone","move something to a later date","We postponed the launch until the images were fixed."),
("terminate","end something formally and completely","We terminated the agreement rather than renegotiate it again."),
("initiate","start something deliberately","I initiated the conversation instead of waiting for him to call."),
("implement","actually put a plan into practice","Everyone likes the plan, nobody wants to implement it."),
("refine","improve something that already works","I refined the bullet points instead of rewriting the whole listing."),
("quantify","put a number on it","Do not tell me it is expensive, quantify it."),
("validate","confirm something holds up under a test","The bench test validated the three wire conversion."),
("undermine","weaken something quietly from underneath","Saying yes to everything undermined my own position."),
("reinforce","make something stronger","Every time I hold the line it reinforces that I mean it."),
("diversify","spread risk across more than one thing","I need to diversify off one channel before it decides my income."),
("optimize","tune something for the best result","We optimize the campaign weekly, not daily."),
("scrutinize","look at something hard and closely","Scrutinize the invoice line by line before you pay it."),
("rectify","fix a wrong thing","They agreed to rectify the shortage on the next shipment."),
("circumvent","get around an obstacle","He tried to circumvent the approval step and it cost us."),
("alleviate","take the pressure off","Paying that card down would alleviate most of the monthly stress."),
("stipulate","state a condition as part of the deal","The contract stipulates payment within thirty days of arrival."),
("exacerbate","make a bad thing worse","Cutting the budget mid launch exacerbated the rank slide."),
("facilitate","make something easier to happen","My job is to facilitate the decision, not to make it for him."),
("delineate","draw a clear line around what is what","Delineate who owns which task before the project starts."),
("reiterate","say it again because it matters","Let me reiterate the deadline so there is no confusion."),
("articulate","put a thought into clear words","I know what I mean, I just have to articulate it faster."),
("advocate","argue publicly for something","I advocate for the cheaper option because it protects cash."),
("deter","stop someone from doing something by raising the cost","A signed agreement deters the casual excuse."),
("endorse","publicly back something or someone","I will endorse the supplier once he hits two clean orders."),
("relinquish","let go of control of something","I had to relinquish the daily uploads to get my evenings back."),
]
