# Tier 2: negotiation and business words
T2 = [
("leverage","use a small thing to move a big thing","My leverage is that he needs the reorder more than I need the discount."),
("contingent","depending on something else happening first","The second payment is contingent on a clean inspection."),
("provisional","temporary, holds until the real version lands","That is a provisional number until the freight invoice arrives."),
("remit","send payment","Please remit the balance by Friday."),
("indemnify","promise to cover someone else's loss","The supplier agreed to indemnify us for defective units."),
("arrears","money that is overdue","The account is ninety days in arrears."),
("escrow","money held by a third party until conditions are met","We put the deposit in escrow until the samples pass."),
("liquidity","how fast you can turn something into cash","Inventory is an asset with terrible liquidity."),
("margin","what is left after cost, per sale","At that price the margin is four dollars, not fourteen."),
("overhead","the cost of running the business no matter what you sell","Overhead eats the profit long before the product does."),
("liability","something you owe or something that can cost you","That unsold pallet is a liability, not inventory."),
("equity","the part you actually own after debts","The equity in the house is real money I am not touching yet."),
("accrue","build up over time","Interest accrues daily on that balance."),
("amortize","spread a cost across the periods it serves","We amortize the tooling cost over the first three orders."),
("procurement","the job of buying what the business needs","Procurement is where the profit is actually made."),
("remittance","a payment you send","The remittance advice shows which invoices it covers."),
("arbitration","settling a dispute outside court with a neutral judge","The contract forces arbitration instead of a lawsuit."),
("breach","breaking a term of the agreement","Missing the ship date twice is a breach, not a hiccup."),
("covenant","a promise written into an agreement","The loan has a covenant that caps new debt."),
("default","failing to do what the agreement required","One missed payment does not trigger default, three do."),
("forbearance","the lender agreeing not to enforce for a while","I asked for forbearance for sixty days instead of missing outright."),
("lien","a legal claim on property until a debt is paid","There is a lien on the vehicle until the note is paid."),
("collateral","what backs a loan if you cannot pay","They wanted collateral I was not willing to pledge."),
("solvency","being able to pay what you owe","Solvency is not the same thing as profit."),
("insolvent","unable to pay your debts","Plenty of profitable companies go insolvent on timing."),
("receivable","money customers owe you","The receivable is real, it just is not cash yet."),
("disbursement","money going out","The disbursement schedule pays the supplier in three parts."),
("valuation","what something is judged to be worth","The valuation was built on a revenue multiple I do not trust."),
("appraisal","a formal opinion of value","The appraisal came in under what I owed."),
("underwrite","take on the risk of something","The bank would not underwrite a business under two years old."),
("surety","a party who guarantees another party's obligation","The parent company acted as surety on the order."),
("recourse","what you can do if the other side fails","Without a signed PO I have no recourse."),
("concession","something you give up to move the deal","I gave one concession on the ship date and held price."),
("stipulation","a specific condition in an agreement","My stipulation was net thirty or no order."),
("mandate","an instruction with authority behind it","The mandate was clear, cut spend twenty percent."),
("jurisdiction","whose rules apply and where","The contract puts jurisdiction in Pennsylvania."),
("quorum","the minimum people needed for a decision to count","We did not have a quorum so nothing was decided."),
("proxy","someone acting with your authority","He signed by proxy while I was out of the country."),
("tariff","a tax on imported goods","The tariff added eleven percent to the landed cost."),
("levy","a charge imposed by an authority","The port levied a storage fee after the free days ran out."),
("rebate","money paid back after the purchase","The rebate came four months after we needed the cash."),
("retainer","money paid up front to hold someone's time","I would rather charge a retainer than bill by the hour."),
("attrition","slow loss over time","Our review count drops by attrition if we stop asking."),
("benchmark","the standard you measure against","My benchmark is the competitor at nineteen eighty eight."),
("remuneration","what someone is paid for their work","Remuneration was never the issue, the hours were."),
("arbitrate","settle a disagreement between two sides","The platform arbitrates the claim, not the seller."),
("consignment","goods you hold but do not own until sold","They offered consignment so I would carry no inventory risk."),
("prorate","split a cost proportionally","We prorated the freight across the two SKUs by weight."),
("reconciliation","the process of making two records agree","The monthly reconciliation is where the errors surface."),
("escalation","a planned rise in price or in urgency","The contract has a price escalation clause tied to material cost."),
]
