# Tier 3: describing people and behavior accurately
T3 = [
("magnanimous","generous toward someone you could have crushed","He was magnanimous about the mistake and never brought it up again."),
("petulant","sulky and irritable over something small","I got petulant about the parking spot and heard myself do it."),
("candid","honest even when it costs you something","Be candid with me, is the ship date real or hopeful?"),
("obstinate","refusing to move for no good reason","He is not principled, he is obstinate."),
("gracious","warm and easy with people, especially when you do not have to be","She was gracious about me being late and it disarmed me."),
("meticulous","careful about every small detail","His carton labeling is meticulous, which is why I use him."),
("abrasive","rubs people the wrong way","My tone gets abrasive when I am tired."),
("affable","easy to talk to","The freight guy is affable, which is worth more than his rate."),
("aloof","distant on purpose","I read her as aloof when she was actually nervous."),
("brusque","blunt to the point of rude","I was brusque on the call and had to walk it back."),
("complacent","comfortable enough to stop trying","Two good months made me complacent."),
("conscientious","does the job right when nobody is watching","She is conscientious, I never have to check her work twice."),
("cordial","polite and friendly without being close","We keep it cordial, we are not friends."),
("deferential","showing respect for someone's authority or judgment","I was deferential to his read on freight because it is his lane."),
("diligent","steady and thorough over time","Diligent beats brilliant on a twelve month project."),
("discreet","careful about what you repeat","He is discreet, which is why people tell him things."),
("dogmatic","holds an opinion like it is a law","Do not be dogmatic about the price until you see the data."),
("evasive","avoids answering straight","He got evasive the second I asked for the invoice."),
("fastidious","fussy about standards and cleanliness","She is fastidious about the kitchen and I respect it."),
("flippant","treating a serious thing lightly","My flippant answer made her think I did not care."),
("forthright","says it straight without hedging","Be forthright about the money instead of hinting."),
("gregarious","enjoys being around people","I used to be gregarious and I want that back."),
("impetuous","acts on impulse without thinking it through","The impetuous version of me closed deals and also lost money."),
("indignant","angry at something you think is unfair","He was indignant about the fee and he was right."),
("ingratiating","trying too hard to be liked","Saying yes to everything came off as ingratiating, not generous."),
("insolent","openly disrespectful","The reply was insolent and I ended the thread."),
("intransigent","will not compromise at all","The supplier was intransigent on MOQ so I walked."),
("judicious","shows good judgment","A judicious no is worth more than an eager yes."),
("laconic","says a lot in very few words","His laconic answers made people lean in."),
("mercurial","mood changes fast and without warning","He is mercurial, so I never negotiate with him after six."),
("morose","gloomy and withdrawn","I get morose when the money is tight and it shows on my face."),
("obsequious","fawning, agreeing with everything to please","Obsequious is what I was, and she felt it."),
("pedantic","obsessed with small correctness","Do not be pedantic about the wording, answer the question."),
("pragmatic","chooses what works over what is ideal","The pragmatic call is air freight half and sea the rest."),
("presumptuous","assuming more access or agreement than you have","It was presumptuous of me to plan her weekend."),
("reticent","holds back, does not volunteer much","She was reticent about her family until the third date."),
("sanctimonious","acting morally superior","Nobody listens to a sanctimonious lecture."),
("scrupulous","strictly honest and careful","He is scrupulous about the count, every carton matches."),
("self-effacing","plays down your own importance","Self effacing is charming until it becomes invisible."),
("stoic","takes hardship without complaining","Stoic is not the same as silent."),
("tactful","says the hard thing without cutting","Be tactful, not soft."),
("tenacious","does not let go","Tenacious on the follow up is how the deal got done."),
("unflappable","stays calm no matter what","She is unflappable, which is why she runs the call."),
("vindictive","wants to get back at someone","A vindictive email costs more than the argument was worth."),
("garrulous","talks too much, mostly about nothing","I get garrulous when I am nervous, that is the tell."),
("glib","smooth talking but shallow","His glib answer told me he had not read the file."),
("humble","honest about your own size without shrinking","Humble is accurate, not small."),
("imperious","bossy in an arrogant way","Imperious gets compliance and kills loyalty."),
("meek","too soft to push back","Meek is what drove her away, not kindness."),
("resolute","fixed on a decision and calm about it","Resolute is what I am rebuilding, decide once and hold."),
]
