# Tier 4: words that make a sentence land harder
T4 = [
("unequivocal","leaves zero room for doubt","My answer is an unequivocal no."),
("categorical","absolute, no exceptions","That is a categorical rule, not a preference."),
("ostensibly","on the surface, but probably not really","He called ostensibly about the invoice, actually about the reorder."),
("notwithstanding","in spite of that","Notwithstanding the delay, the numbers still work."),
("invariably","every single time","He invariably asks for a discount at the end of the call."),
("inherently","by its own nature","Air freight is inherently more expensive, that is not a surprise."),
("fundamentally","at the root of it","Fundamentally this is a structure problem, not a vocabulary problem."),
("decisively","in a way that settles it","Move decisively or do not move."),
("explicitly","stated out loud, in plain words","I explicitly said no new spend this week."),
("implicitly","understood without being said","By saying yes I implicitly agreed to the whole thing."),
("conclusively","proven, argument over","The bench test settled it conclusively."),
("demonstrably","you can show it, not just claim it","That listing is demonstrably converting better since the rewrite."),
("patently","obviously, to anyone looking","That quote is patently above market."),
("manifestly","clearly and visibly","He is manifestly not ready to ship on time."),
("arguably","you could make a case for it","That is arguably the best photo in the set."),
("ultimately","when everything settles out","Ultimately the price is what decides it."),
("consequently","because of that","We missed the cutoff, consequently the pallet sits a week."),
("accordingly","in line with that","The data changed, so I adjusted the bid accordingly."),
("nevertheless","even so","It was expensive, nevertheless it was the right call."),
("regardless","no matter what else","Regardless of the excuse, the deadline stands."),
("precisely","exactly, no rounding","That is precisely the problem I was describing."),
("squarely","directly and without dodging","The blame sits squarely with me."),
("wholly","entirely","That claim is wholly unsupported."),
("markedly","noticeably more or less","Conversion is markedly better on the new main image."),
("substantially","by a large amount","Landed cost went up substantially after the tariff."),
("negligible","so small it does not matter","The difference is negligible, do not spend an hour on it."),
("marginal","barely enough to count","The gain is marginal and the risk is not."),
("pivotal","the point everything turns on","The inspection is the pivotal step."),
("paramount","above everything else","Cash flow is paramount right now."),
("tantamount","effectively the same as","Silence here is tantamount to agreement."),
("requisite","required for the thing to happen","He does not have the requisite volume for that price."),
("imperative","must happen, not optional","It is imperative we ship before the holiday cutoff."),
("indispensable","cannot do without it","She is indispensable on that account."),
("redundant","repeated with no added value","Half those bullet points are redundant."),
("superfluous","more than is needed","The extra packaging is superfluous and costs us margin."),
("untenable","cannot be defended or held","Carrying both at that price is untenable."),
("tenable","can be held or defended","At nineteen eighty eight the position is tenable."),
("viable","can actually work","One channel is not a viable business."),
("plausible","believable on its face","The excuse is plausible, it is still an excuse."),
("dubious","doubtful, probably not right","His unit count is dubious."),
("spurious","fake or based on a false link","That is a spurious correlation, sales moved for another reason."),
("irrefutable","cannot be argued against","The settlement report is irrefutable, the fee is wrong."),
("incontrovertible","beyond dispute","The photos are incontrovertible, the carton was crushed."),
("palpable","you can almost feel it","The tension in that call was palpable."),
("salient","the point that stands out","The salient issue is timing, not price."),
("germane","directly relevant","That is interesting but not germane to the decision."),
("extraneous","off topic, does not belong","Cut the extraneous detail and give me the number."),
("prohibitive","so expensive it stops you","Air freight on that weight is prohibitive."),
("nominal","in name only, or tiny in amount","There is a nominal fee, about two dollars."),
("disproportionate","way out of scale with the cause","My reaction was disproportionate to what she actually said."),
]
