# Tier 5: precision nouns for ideas
T5 = [
("premise","the thing an argument is built on","Your premise is wrong, so the conclusion does not matter."),
("corollary","something that follows automatically from the main point","The corollary is that we cannot raise price and cut ads at once."),
("precedent","an earlier case that sets the pattern","If I discount now I set a precedent for every order after."),
("threshold","the line where something starts to count","Below fifty units it is under my threshold to care."),
("disposition","someone's usual temperament, or how a matter gets settled","His disposition is calm, which is why he handles the angry calls."),
("criterion","a single standard used to judge","My only criterion is whether it clears five hundred a month."),
("paradigm","the whole model of how something works","Selling on one channel is an old paradigm."),
("rationale","the reasoning behind a decision","Give me the rationale, not just the number."),
("caveat","a warning attached to the answer","The caveat is that this assumes the tariff does not change."),
("nuance","a small difference that changes the meaning","There is a nuance between firm and rigid."),
("discrepancy","two things that should match and do not","There is a discrepancy of four hundred between the invoice and the wire."),
("anomaly","a one off that breaks the pattern","One good day is an anomaly, not a trend."),
("correlation","two things moving together","Correlation is not enough to move budget."),
("causation","one thing actually causing the other","Prove causation before you scale the spend."),
("inference","a conclusion you draw from evidence","My inference is that he is out of stock, he never said so."),
("conjecture","a guess with no evidence behind it","That is conjecture, find the report."),
("hypothesis","a testable guess","My hypothesis is that the main image is the bottleneck."),
("consensus","general agreement in a group","We reached consensus without anyone loving it."),
("dichotomy","a split into two opposed parts","The dichotomy between saying yes and being kind is false."),
("paradox","two true things that seem to contradict","The paradox is that saying no made her want me more."),
("analogy","explaining one thing by comparing it to another","Use an analogy when the numbers alone will not land."),
("aggregate","the total, everything added together","In aggregate the account is profitable, per SKU it is not."),
("variance","how much something swings from the expected","The variance week to week is bigger than the trend."),
("trajectory","the path something is on","The trajectory is fine, the current number is not."),
("magnitude","how big the thing is","We agree on direction, we disagree on magnitude."),
("parameter","a boundary you set for the work","Set the parameters before you start or it never ends."),
("constraint","a hard limit you must work inside","Cash is the constraint, not ideas."),
("contingency","a backup plan for if it goes wrong","My contingency is air freight on half the units."),
("ramification","a downstream consequence","The ramification of a stockout is rank, not just lost sales."),
("implication","what it means for everything else","The implication is that we reorder six weeks earlier."),
("prerequisite","something required before you can start","A clean inspection is a prerequisite for the second payment."),
("catalyst","the thing that sets it off","The price cut was the catalyst for the whole recovery."),
("impetus","the push that gets it moving","The tariff was the impetus to find a second supplier."),
("momentum","the force you build by keeping going","Momentum is the whole point of a daily habit."),
("scope","how far the work reaches","Keep the scope tight or the project eats the month."),
("latitude","room to make your own call","Give him latitude on the design, not on the deadline."),
("leeway","slack in the schedule or the rules","There is no leeway on the holiday cutoff."),
("baseline","the starting number you measure from","Take a baseline recording before you change anything."),
("deviation","how far off the standard you drifted","Any deviation from the spec gets flagged at inspection."),
("propensity","a tendency to do something","I have a propensity to say yes before I have thought."),
("prevalence","how widespread something is","The prevalence of that defect decides whether we recall."),
("equilibrium","the point where forces balance","Price finds equilibrium once both of us stop moving."),
("juncture","a point in time where a decision has to be made","At this juncture I either reorder or I let it go."),
("crux","the heart of the matter","The crux is that I never asked her for anything."),
("tenet","a core belief a system runs on","A tenet of the plan is that I never touch the emergency fund."),
("axiom","something taken as obviously true","It is an axiom here that cash beats revenue."),
("doctrine","a settled body of rules and beliefs","Our PPC doctrine says never pause, bid down instead."),
("framework","a structure for thinking about something","Use a framework so you are not composing live."),
("synthesis","combining parts into one coherent whole","The synthesis of both reads is that we hold price."),
("distinction","the specific difference between two things","The distinction between firm and cold is the whole game."),
]
