# Tier 6: social and warmth words
T6 = [
("rapport","an easy connection where talking feels natural","We built rapport before I asked him for anything."),
("deference","treating someone's judgment as worth more than yours in their lane","Show deference on freight, he knows it better than I do."),
("earnest","serious and sincere, not performing","Ask the question earnest, not clever."),
("obliging","willing to help without being asked twice","He was obliging about the reship and I noticed."),
("generous","gives more than the situation required","Be generous with credit, tight with promises."),
("empathy","feeling what the other person is feeling","Empathy is not agreement, it is understanding."),
("camaraderie","the easy loyalty between people who do the same hard thing","There is camaraderie between sellers that nobody outside gets."),
("goodwill","the credit you build by being decent over time","Goodwill is the only thing that survives a bad quarter."),
("reciprocity","the pull to give back after receiving","Asking for a small favor triggers reciprocity, giving does not."),
("cordiality","warm politeness","Cordiality costs nothing and opens doors."),
("warmth","the felt sense that you are glad they are there","Warmth is the thing people remember, not the words."),
("sincerity","meaning what you say","Sincerity is the difference between a compliment and flattery."),
("gratitude","actually feeling thankful, not just saying it","I told him specifically what I was grateful for, not just thanks."),
("humility","an accurate view of your own size","Humility is not shrinking, it is not inflating."),
("tact","saying the hard thing without leaving a mark","Tact is timing plus word choice."),
("poise","staying composed when it would be easy not to","She held her poise through the whole complaint."),
("composure","calm under pressure","I lost composure and that was the real mistake."),
("charisma","the pull that makes people want to be near you","Charisma is mostly presence and attention."),
("levity","lightness that breaks the tension","A little levity saved that meeting."),
("banter","quick playful back and forth","Banter is how I used to open and I want it back."),
("repartee","fast, clever conversational comeback","Repartee is not insults, it is timing."),
("wit","fast intelligence that lands as funny","Wit is the cheapest status there is."),
("charm","making people feel good in your company","Charm is attention pointed at them, not performance about you."),
("grace","handling something awkward without making it worse","She handled my mistake with grace."),
("courtesy","the small respectful things you do by default","Courtesy is a habit, not a mood."),
("hospitality","making someone feel welcome in your space","Hospitality is why people come back."),
("solidarity","standing with someone publicly","I showed solidarity instead of quietly agreeing later."),
("kinship","the feeling of being the same kind of person","There was instant kinship, we both build things alone."),
("allegiance","loyalty you have chosen and stated","My allegiance is to the plan, not the mood."),
("loyalty","staying with someone when it costs you","Loyalty is proven in the inconvenient moment."),
("trust","the belief that someone will do what they said","Trust is built by small kept promises, not big ones."),
("candor","open honesty, even when it is awkward","Candor early prevents a fight later."),
("vulnerability","letting someone see a real weak spot","Vulnerability is strength when it is chosen, not leaked."),
("presence","being fully there with the person in front of you","Presence beats every clever line."),
("attentive","noticing and responding to what they need","Be attentive without hovering."),
("receptive","open to what someone is offering","She was receptive because I asked instead of told."),
("approachable","easy for people to come talk to","Approachable is a posture, not a personality."),
("engaging","holds attention in a good way","He is engaging because he asks better questions."),
("disarming","takes the defensiveness out of someone","A disarming admission ended the whole argument."),
("magnetic","people move toward you without knowing why","Magnetic is what I used to be at a table of strangers."),
("genuine","real, not put on","People can tell genuine from performed in about four seconds."),
("considerate","thinks about the effect on other people","Considerate is small and constant, not grand."),
("thoughtful","puts real thought into what someone needs","A thoughtful question beats an expensive gift."),
("supportive","backs someone up in a way they can feel","Supportive means showing up, not agreeing with everything."),
("encouraging","gives someone the push to keep going","Be encouraging about effort, specific about results."),
("appreciative","showing you value what someone did","Appreciative and specific, always both."),
("acknowledgment","openly noticing what someone did or said","Acknowledgment is the cheapest thing that lands the hardest."),
("validation","confirming someone's feeling is reasonable","Validation is not agreement, it is recognition."),
("affirmation","stating out loud that someone is what they are","Give people a reputation to live up to."),
("connection","the sense of being part of each other's life","Connection comes from asking, not from giving."),
]
